In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Nama Kelompok - Machine Learning
- Yudhistira Kusuma 202310067
- Michael Mervin Ruswan 202310016
- Fajar Alfiantino 202310072

In [ ]:
# Loading the libraries
import numpy as np
import pandas as pd
from sklearn import datasets, tree
from sklearn.metrics import silhouette_score, confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.cluster import DBSCAN, KMeans, AgglomerativeClustering
from sklearn.neighbors import KNeighborsClassifier
from matplotlib import pyplot as plt

In [ ]:
## Load Dataset from CSV
csv = '/content/drive/MyDrive/MachineLearning/UTS/mobileprice_modified.csv'
dataset = pd.read_csv(csv)

## Nomor 2 - Praproses Data

### Real Value

In [ ]:
# Tampilkan statistik deskriptif sebelum pengisian missing value dan standarisasi
# Statistik deskriptif => cabang dari statistik untuk mendeskripsikan dan merangkum data.
# 2 jenis statistik deskriptif => Measures of Central Tendency (mean, median, modus), Measures of Spread (std, kuartil)

deskripsi_awal = dataset.describe()
print("Statistik Deskriptif Sebelum Pengisian Missing Value dan Standarisasi:")
print(deskripsi_awal)

Statistik Deskriptif Sebelum Pengisian Missing Value dan Standarisasi:
       battery_power       blue  clock_speed     dual_sim           fc  \
count    1990.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1237.867839     0.4950     1.522250     0.509500     4.309500   
std       439.676025     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       850.250000     0.0000     0.700000     0.000000     1.000000   
50%      1225.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.000000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  1990.000000  2000.000000  1990.000000  2000.000000  ...   
mean      0.521500    31.987940     0.501750   140.344221     4.520500  ...   
std       0.499662    18.

In [ ]:
print(dataset.shape)

(2000, 21)


In [ ]:
print(dataset)
dataset.isna().sum()

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0             842.0     0          2.2         0   1       0         7.0   
1            1021.0     1          0.5         1   0       1        53.0   
2             563.0     1          0.5         1   2       1        41.0   
3             615.0     1          2.5         0   0       0        10.0   
4            1821.0     1          1.2         0  13       1        44.0   
...             ...   ...          ...       ...  ..     ...         ...   
1995          794.0     1          0.5         1   0       1         2.0   
1996         1965.0     1          2.6         1   0       0        39.0   
1997         1911.0     0          0.9         1   1       1        36.0   
1998         1512.0     0          0.9         0   4       1        46.0   
1999          510.0     1          2.0         1   5       1        45.0   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width     ram  sc_h  sc_w  \
0     

battery_power    10
blue              0
clock_speed       0
dual_sim          0
fc                0
four_g            0
int_memory       10
m_dep             0
mobile_wt        10
n_cores           0
pc                0
px_height         0
px_width          0
ram              10
sc_h              0
sc_w              0
talk_time         0
three_g           0
touch_screen      0
wifi              0
price_range       0
dtype: int64

### Standard Scaler

In [ ]:
# Pisahkan atribut prediktor dan atribut label
X = dataset.drop("price_range", axis=1)  # Atribut prediktor
y = dataset["price_range"]  # Atribut label

# Inisialisasi SimpleImputer menggunakan median sebagai strategi pengisian nilai
imputer = SimpleImputer(strategy="median")

# Inisialisasi StandardScaler untuk mengubah nilai atribut prediktor agar nilai
# dari masing-masing atribut seragam
scaler = StandardScaler()

# Imputasi missing value dan Lakukan standarisasi menggunakan StandardScaling Scaling pada atribut prediktor yang sudah diimputasi
X_imputed = imputer.fit_transform(X)
X_scaled = scaler.fit_transform(X_imputed)

# Konversi hasil transformasi kembali ke Pandas DataFrame (opsional)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

# Gabungkan atribut prediktor yang sudah diimputasi dan distandarisasi dengan atribut label
data_scaled = pd.concat([X_scaled_df, y], axis=1)

# Tampilkan statistik deskriptif setelah pengisian missing value dan standarisasi
deskripsi_setelah = data_scaled.describe()
print("\nStatistik Deskriptif Setelah Pengisian Missing Value dan Standarisasi (Menggunakan StandardScaler):")
print(deskripsi_setelah)


Statistik Deskriptif Setelah Pengisian Missing Value dan Standarisasi (Menggunakan StandardScaler):
       battery_power          blue   clock_speed      dual_sim            fc  \
count   2.000000e+03  2.000000e+03  2.000000e+03  2.000000e+03  2.000000e+03   
mean    2.842171e-17 -1.243450e-17 -1.545430e-16  8.082424e-17  5.861978e-17   
std     1.000250e+00  1.000250e+00  1.000250e+00  1.000250e+00  1.000250e+00   
min    -1.680411e+00 -9.900495e-01 -1.253064e+00 -1.019184e+00 -9.928904e-01   
25%    -8.804636e-01 -9.900495e-01 -1.007906e+00 -1.019184e+00 -7.624947e-01   
50%    -2.920066e-02 -9.900495e-01 -2.727384e-02  9.811771e-01 -3.017032e-01   
75%     8.579829e-01  1.010051e+00  8.307794e-01  9.811771e-01  6.198797e-01   
max     1.733763e+00  1.010051e+00  1.811412e+00  9.811771e-01  3.384628e+00   

             four_g    int_memory         m_dep     mobile_wt       n_cores  \
count  2.000000e+03  2.000000e+03  2.000000e+03  2.000000e+03  2.000000e+03   
mean   1.048051e-16 

### MinMax Scaler

In [ ]:
# Pisahkan atribut prediktor
X = dataset.drop("price_range", axis=1)  # Atribut prediktor yang akan diimputasi

# Inisialisasi Min-Max Scaler dan Simple Imputer
scaler = MinMaxScaler()
imputer = SimpleImputer(strategy="median")

# Imputasi missing value dengan median
X_imputed = imputer.fit_transform(X)

# Lakukan standarisasi menggunakan Min-Max Scaling pada atribut prediktor yang sudah diimputasi
X_scaled = scaler.fit_transform(X_imputed)

# Konversi hasil transformasi kembali ke Pandas DataFrame (opsional)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

# Gabungkan atribut prediktor yang sudah diimputasi dan distandarisasi dengan atribut label
data_scaled = pd.concat([X_scaled_df, y], axis=1)

# Tampilkan statistik deskriptif setelah pengisian dan standarisasi
deskripsi_setelah = data_scaled.describe()
print("Statistik Deskriptif Setelah Pengisian dan Standarisasi (Menggunakan MinMaxScaler):")
print(deskripsi_setelah)

Statistik Deskriptif Setelah Pengisian dan Standarisasi (Menggunakan MinMaxScaler):
       battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean        0.492187     0.4950     0.408900     0.509500     0.226816   
std         0.292970     0.5001     0.326402     0.500035     0.228497   
min         0.000000     0.0000     0.000000     0.000000     0.000000   
25%         0.234302     0.0000     0.080000     0.000000     0.052632   
50%         0.483634     0.0000     0.400000     1.000000     0.157895   
75%         0.743487     1.0000     0.680000     1.000000     0.368421   
max         1.000000     1.0000     1.000000     1.000000     1.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500     0.483677     0.446389     0.502896     0.502929  ...   
std       0.

## Nomor 3 - Classification

### Decision Tree

In [ ]:
# Pisahkan atribut prediktor dan atribut label
X = dataset.drop("price_range", axis=1)  # Atribut prediktor
y = dataset["price_range"]  # Atribut label

# Inisialisasi SimpleImputer untuk mengisi nilai-nilai yang hilang dengan median
imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X)

# Bagi data menjadi data latih (80%) dan data uji (20%) dengan metode holdout
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model Decision Tree
decision_tree_model = DecisionTreeClassifier()

# Latih model Decision Tree menggunakan data latih
decision_tree_model.fit(X_train, y_train)

# Prediksi label pada data uji
y_pred = decision_tree_model.predict(X_test)

# Hitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model: {:.2f}%".format(accuracy * 100))
class_report = classification_report(y_test, y_pred)

# Tampilkan confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("Laporan Klasifikasi:\n", class_report)

Akurasi Model: 81.50%
Confusion Matrix:
[[89 16  0  0]
 [ 7 75  9  0]
 [ 0 16 63 13]
 [ 0  0 13 99]]
Laporan Klasifikasi:
               precision    recall  f1-score   support

           0       0.93      0.85      0.89       105
           1       0.70      0.82      0.76        91
           2       0.74      0.68      0.71        92
           3       0.88      0.88      0.88       112

    accuracy                           0.81       400
   macro avg       0.81      0.81      0.81       400
weighted avg       0.82      0.81      0.82       400



### KNN

In [ ]:
# Pisahkan atribut prediktor dan atribut label
X = dataset.drop("price_range", axis=1)  # Atribut prediktor
y = dataset["price_range"]  # Atribut label

# Inisialisasi SimpleImputer untuk mengisi nilai-nilai yang hilang dengan median
imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X)

# Bagi data menjadi data latih (80%) dan data uji (20%) dengan metode holdout
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model KNN
knn_model = KNeighborsClassifier(n_neighbors=25)  # Ganti nilai n_neighbors sesuai kebutuhan, 25 terbaik, 94,75% (?)

# Latih model KNN menggunakan data latih
knn_model.fit(X_train, y_train)

# Prediksi label pada data uji
y_pred = knn_model.predict(X_test)

# Hitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model: {:.2f}%".format(accuracy * 100))
class_report = classification_report(y_test, y_pred)

# Tampilkan confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("Laporan Klasifikasi:\n", class_report)

Akurasi Model: 94.75%
Confusion Matrix:
[[102   3   0   0]
 [  2  87   2   0]
 [  0   4  86   2]
 [  0   0   8 104]]
Laporan Klasifikasi:
               precision    recall  f1-score   support

           0       0.98      0.97      0.98       105
           1       0.93      0.96      0.94        91
           2       0.90      0.93      0.91        92
           3       0.98      0.93      0.95       112

    accuracy                           0.95       400
   macro avg       0.95      0.95      0.95       400
weighted avg       0.95      0.95      0.95       400



### SVM

In [ ]:
# Pisahkan atribut prediktor dan atribut label
X = dataset.drop("price_range", axis=1)  # Atribut prediktor yang sudah diimputasi dan distandarisasi
y = dataset["price_range"]  # Atribut label

# Inisialisasi SimpleImputer dan StandardScaler
imputer = SimpleImputer(strategy="median")
scaler = StandardScaler()

# Imputasi missing value dan standarisasi atribut prediktor
X_imputed = imputer.fit_transform(X)
X_scaled = scaler.fit_transform(X_imputed)

# Inisialisasi model SVM (Support Vector Machine) dengan kernel linear
svm_model = SVC(kernel='linear')

# Bagi data menjadi data latih (80%) dan data uji (20%) dengan metode holdout
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Latih model SVM menggunakan data latih
svm_model.fit(X_train, y_train)

# Prediksi label pada data uji
y_pred = svm_model.predict(X_test)

# Evaluasi model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Tampilkan hasil evaluasi
print("Akurasi: {:.2f}%".format(accuracy * 100))
print("Matriks Konfusi:\n", conf_matrix)
print("Laporan Klasifikasi:\n", class_report)

Akurasi: 96.00%
Matriks Konfusi:
 [[ 97   8   0   0]
 [  0  90   1   0]
 [  0   3  86   3]
 [  0   0   1 111]]
Laporan Klasifikasi:
               precision    recall  f1-score   support

           0       1.00      0.92      0.96       105
           1       0.89      0.99      0.94        91
           2       0.98      0.93      0.96        92
           3       0.97      0.99      0.98       112

    accuracy                           0.96       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.96      0.96      0.96       400



## Nomor 4 - Clustering

### Agglomerative Clustering

In [ ]:
# Pisahkan atribut prediktor
X = dataset.drop("price_range", axis=1)  # Atribut prediktor

# Inisialisasi SimpleImputer untuk mengisi nilai-nilai yang hilang dengan median
imputer = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

# Inisialisasi model Agglomerative Clustering
num_clusters_range = range(2,8)  # Ganti dengan jumlah cluster yang ingin dicoba
linkage_methods = ['ward', 'complete', 'average', 'single']  # Ganti dengan metode penggabungan yang ingin dicoba

best_silhouette_score = -1  # Inisialisasi skor Silhouette terbaik
best_config = None  # Inisialisasi konfigurasi terbaik

# Loop melalui variasi jumlah cluster dan metode penggabungan
for num_clusters in num_clusters_range:
    for linkage_method in linkage_methods:
        # Inisialisasi model Agglomerative Clustering
        agg_model = AgglomerativeClustering(n_clusters=num_clusters, linkage=linkage_method)

        # Lakukan klustering dengan Agglomerative Clustering
        labels = agg_model.fit_predict(X_imputed)

        # Hitung Silhouette Score
        silhouette_avg = silhouette_score(X_imputed, labels)

        # Cetak hasil
        print(f"Number of Clusters: {num_clusters}, Linkage Method: {linkage_method}, Silhouette Score: {silhouette_avg}")

        # Periksa apakah hasil saat ini lebih baik
        if silhouette_avg > best_silhouette_score:
            best_silhouette_score = silhouette_avg
            best_config = (num_clusters, linkage_method)

print("Best Configuration:")
print(f"Number of Clusters: {best_config[0]}, Linkage Method: {best_config[1]}")
print("Best Silhouette Score:", best_silhouette_score)

Number of Clusters: 2, Linkage Method: ward, Silhouette Score: 0.3794387610344186
Number of Clusters: 2, Linkage Method: complete, Silhouette Score: 0.3697867898618279
Number of Clusters: 2, Linkage Method: average, Silhouette Score: 0.376730003158973
Number of Clusters: 2, Linkage Method: single, Silhouette Score: 0.12523571232387107
Number of Clusters: 3, Linkage Method: ward, Silhouette Score: 0.24772147110710824
Number of Clusters: 3, Linkage Method: complete, Silhouette Score: 0.24078691471030247
Number of Clusters: 3, Linkage Method: average, Silhouette Score: 0.2499049214577642
Number of Clusters: 3, Linkage Method: single, Silhouette Score: 0.07681025030009409
Number of Clusters: 4, Linkage Method: ward, Silhouette Score: 0.19291302141421546
Number of Clusters: 4, Linkage Method: complete, Silhouette Score: 0.1967349543175183
Number of Clusters: 4, Linkage Method: average, Silhouette Score: 0.19946383471130555
Number of Clusters: 4, Linkage Method: single, Silhouette Score: -0.

### DBScan

In [ ]:
# Pisahkan atribut prediktor
X = dataset.drop("price_range", axis=1)  # Atribut prediktor

# Inisialisasi SimpleImputer untuk mengisi nilai-nilai yang hilang dengan median
imputer = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

# Inisialisasi StandardScaler untuk standarisasi atribut prediktor
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

# Range nilai eps dan min_samples yang ingin dicoba
eps_values = [4.0, 4.35, 4.5, 4.65]  # Ganti dengan nilai eps yang ingin dicoba
min_samples_values = [20, 30, 40, 50]  # Ganti dengan nilai min_samples yang ingin dicoba

best_silhouette_score = -1  # Inisialisasi skor Silhouette terbaik
best_eps = None  # Inisialisasi nilai eps terbaik
best_min_samples = None  # Inisialisasi nilai min_samples terbaik

for eps in eps_values:
    for min_samples in min_samples_values:
        # Inisialisasi model DBSCAN dengan parameter yang disesuaikan
        dbscan_model = DBSCAN(eps=eps, min_samples=min_samples)

        # Lakukan klustering dengan DBSCAN
        labels = dbscan_model.fit_predict(X_scaled)

        # Hitung Silhouette Score
        silhouette_avg = silhouette_score(X_scaled, labels)

        # Tampilkan hasil
        print(f"eps: {eps}, min_samples: {min_samples}, Silhouette Score: {silhouette_avg}")

        # Periksa apakah hasil saat ini lebih baik
        if silhouette_avg > best_silhouette_score:
            best_silhouette_score = silhouette_avg
            best_eps = eps
            best_min_samples = min_samples

print("Best Configuration:")
print(f"eps: {best_eps}, min_samples: {best_min_samples}")
print("Best Silhouette Score:", best_silhouette_score)

eps: 4.0, min_samples: 20, Silhouette Score: 0.023588216255901122
eps: 4.0, min_samples: 30, Silhouette Score: 0.051242108900158484
eps: 4.0, min_samples: 40, Silhouette Score: 0.03560687181759633
eps: 4.0, min_samples: 50, Silhouette Score: 0.01766015885450677
eps: 4.35, min_samples: 20, Silhouette Score: 0.12264845314750267
eps: 4.35, min_samples: 30, Silhouette Score: 0.11160132137320525
eps: 4.35, min_samples: 40, Silhouette Score: 0.09995934950750388
eps: 4.35, min_samples: 50, Silhouette Score: 0.09098370687212781
eps: 4.5, min_samples: 20, Silhouette Score: 0.1374837222320706
eps: 4.5, min_samples: 30, Silhouette Score: 0.1386198864936266
eps: 4.5, min_samples: 40, Silhouette Score: 0.11918878221428339
eps: 4.5, min_samples: 50, Silhouette Score: 0.11275756066740253
eps: 4.65, min_samples: 20, Silhouette Score: 0.15587933570561763
eps: 4.65, min_samples: 30, Silhouette Score: 0.15587933570561763
eps: 4.65, min_samples: 40, Silhouette Score: 0.15587933570561763
eps: 4.65, min_sam

### K-Means

In [ ]:
# Pisahkan atribut prediktor
X = dataset.drop("price_range", axis=1)  # Atribut prediktor

# Inisialisasi SimpleImputer untuk mengisi nilai-nilai yang hilang dengan median
imputer = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

# Range jumlah kluster yang ingin dicoba
num_clusters_range = range(2, 8)  # Coba dari 2 hingga 7 kluster

# Inisialisasi nilai n_init yang ingin digunakan
n_init_value = 10  # Ganti dengan nilai n_init yang Anda inginkan

best_silhouette_score = -1  # Inisialisasi skor Silhouette terbaik

for num_clusters in num_clusters_range:
    # Inisialisasi model K-Means dan setel n_init secara eksplisit
    kmeans_model = KMeans(n_clusters=num_clusters, n_init=n_init_value)

    # Lakukan klustering dengan K-Means
    labels = kmeans_model.fit_predict(X_imputed)

    # Hitung Silhouette Score
    silhouette_avg = silhouette_score(X_imputed, labels)

    # Tampilkan hasil
    print(f"Number of Clusters: {num_clusters}, Silhouette Score: {silhouette_avg}")

    # Periksa apakah hasil saat ini lebih baik
    if silhouette_avg > best_silhouette_score:
      best_silhouette_score = silhouette_avg
      best_config = num_clusters

print("Best Configuration:")
print(f"Number of Clusters: {best_config}")
print("Best Silhouette Score:", best_silhouette_score)

Number of Clusters: 2, Silhouette Score: 0.3983422741001593
Number of Clusters: 3, Silhouette Score: 0.27794814569235043
Number of Clusters: 4, Silhouette Score: 0.2620004173839964
Number of Clusters: 5, Silhouette Score: 0.24263073582900407
Number of Clusters: 6, Silhouette Score: 0.22662952026243344
Number of Clusters: 7, Silhouette Score: 0.22627946273518137
Best Configuration:
Number of Clusters: 2
Best Silhouette Score: 0.3983422741001593
